### ISSUE TITLE
Original sources

### ISSUE THREAD

**Issue by pingdynasty** [SamuraiCrow/oXML#1]
Hello Sam,

Thank you for putting this up. I'm the original author of o:XML, I might be able to find some of the missing pieces and source code. Reach me here: martin at rebeltech dot org

best regards,

Martin Klang

**Comment by SamuraiCrow** [comment]
Message sent!

**Comment by pingdynasty** [comment]
Here is a snapshot of the ObjectBox repo: https://github.com/pingdynasty/ObjectBox
